export const root: string;
export const actions: string;
export const avatar: string;
export const large: string;
export const info: string;
export const name: string;
export const score: string;
export const negative: string;
export const positive: string;
